config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#index'

  #dashboard
  get "/dashboard" => 'dashboards#index'

  #user tasks
  resources :tasks
  
  #agent configuration
  namespace :agent, path: '/master' do
    get "/" => "dashboards#index", as: 'master'
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  include AASM
  enum status: [:pending, :working, :complete, :rejected]
  belongs_to :user

  aasm do
    event :completed do
      transitions :from => :working, :to => :complete
    end
  end

  def mark_completed?
    if self.complete?
      #we need join table here
      balance = (self.user.hands - 1)
      self.user.update(hands: balance)
  end
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :agent]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks
end

app/controllers/agent/dashboards_controller.rb
class Agent::DashboardsController < AgentController
  
  def index
    #code
  end
end

app/controllers/agent/tasks_controller.rb
class Agent::TasksController < AgentController

  def index
    @tasks = Task.all
  end
end

app/controllers/agent_controller.rb
class AgentController < ApplicationController
  before_filter :require_agent
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include Authenticable
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :require_normal_user
  before_filter :set_user, only: [:index, :new, :create, :show]

  def index
    @tasks = @user.tasks
  end

  def new
    @task ||= Task.new
  	render
  end

  def create
    @task = @user.tasks.new task_params
    if @task.save
      redirect_to tasks_path, notice: "Task successfully created!"
    else
      render 'new'
    end
  end

  def show
    @task = @user.tasks.find(params[:id])
  end

  private

    def set_user
      @user = current_user
    end

    def task_params
      params.require(:task).permit(:user_id, :title, :description, :status)
    end
end

app/helpers/agent/dashboards_helper.rb
module Agent::DashboardsHelper
end

app/helpers/agent/tasks_helper.rb
module Agent::TasksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/dashboards/index.html.erb
<h1>Dashboards#index</h1>
<p>Find me in app/views/dashboards/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Supahands</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

<% if user_signed_in? && current_user.user? %>
  <%= link_to "dashboard", dashboard_path %>
<% elsif user_signed_in? && current_user.agent? %>
  <%= link_to "agent dashboard", agent_master_path %>
<% else %>
  <%= link_to "login", new_user_session_path %><br/>
  <%= link_to "register", new_user_registration_path %>
<% end %>